import Head from "next/head";
import Link from "next/link";
import {
  Box,
  Grid,
  GridItem,
  Flex,
  Circle,
  Text,
  Editable,
  EditableInput,
  EditableControls,
  EditablePreview,
  useEditableControls,
  IconButton,
  CheckIcon,
  CloseIcon,
  ButtonGroup,
  EditIcon,
  Button,
  Divider,
} from "@chakra-ui/react";
import { NavBar } from "../components/navbar";
import PostCarousel from "../components/postcarousel";
import { arr } from "./homepage";
import { MemberCard } from "../components/membercard";
export default function StudentProfile() {
  const EditableControls = () => {
    const { isEditing, getSubmitButtonProps, getEditButtonProps } =
      useEditableControls();
    return isEditing ? (
      <Button
        _hover={{
          bg: "#600008",
        }}
        color="#ffffff"
        bg="#AE0032"
        h="1.75rem"
        size="sm"
        {...getSubmitButtonProps()}
      >
        OK
      </Button>
    ) : (
      <Flex ml={3} justifyContent="center">
        <Button
          isDisabled
          _hover={{
            bg: "#600008",
          }}
          color="#ffffff"
          bg="#AE0032"
          h="1.75rem"
          size="sm"
          {...getEditButtonProps()}
        >
          Edit
        </Button>
      </Flex>
    );
  };
  return (
    <Box w="100%" h="100vh">
      <Head>
        <title>CRUx Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid
        overflow="hidden"
        h="93vh"
        templateRows="repeat(12, 1fr)"
        templateColumns="repeat(12, 1fr)"
        gap={0}
      >
        <GridItem colSpan={12} rowSpan={3} bg="#C4C4C4">
          <Box
            display="flex"
            h="31vh"
            flexGrow="1"
            bg={`url(${"https://source.unsplash.com/qTLyiHW1nIc/1440x960"})`}
            backgroundSize="cover"
            backgroundRepeat="no-repeat"
            backgroundPosition="center"
          />
        </GridItem>
        <GridItem colSpan={12} rowSpan={2} bg="#E5E5E5">
          <Flex
            flexDir="column"
            h="15.5vh"
            flexGrow="1"
            justify="flex-end"
            align="center"
          >
            <Circle shadow="lg" m={2} bg="white" size="25vh" />
            <Editable
              display="flex"
              justifyContent="center"
              alignItems="center"
              textAlign="center"
              defaultValue="Club Name"
              fontSize="2xl"
              isPreviewFocusable={false}
            >
              <Flex justify="space-between" align="center">
                <Flex h={10} align="center" justify="center">
                  <EditablePreview
                    textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                    fontWeight="extrabold"
                    m={2}
                    mb={5}
                    h={8}
                  />
                  <EditableInput m={2} h={8} />
                </Flex>
                <Flex align="center" justify="flex-start" h={10}>
                  <EditableControls />
                </Flex>
              </Flex>
            </Editable>
          </Flex>
        </GridItem>
        <GridItem
          display="flex"
          justifyContent="flex-start"
          alignItems="center"
          flexDirection="column"
          rowSpan={7}
          colSpan={3}
          bg="#E5E5E5"
        >
          <Box
            mt={3}
            display="flex"
            justifyContent="center"
            alignItems="center"
            textAlign="center"
            borderRadius="2vw"
            shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            bg="#AE0032"
            w="23vw"
            h="4vh"
          >
            <Text
              fontStyle="normal"
              fontWeight="bold"
              fontSize="1.5vh"
              color="#ffffff"
              lineHeight="22px"
              display="flex"
              alignItems="center"
              textAlign="center"
              textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            >
              All Posts
            </Text>
          </Box>
          <Flex
            borderRadius="2vw"
            shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            ml={3}
            mr={3}
            bg="#ffffff"
            w="23vw"
            h="20rem"
            justify="center"
            align="center"
            flexDir="column"
          >
            <Box
              shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              ml={3}
              mr={3}
              bg="#ffffff"
              w="20vw"
              h="15rem"
            >
              <PostCarousel />
            </Box>
          </Flex>
        </GridItem>
        <GridItem
          rowSpan={7}
          flexGrow="initial"
          overflowX="hidden"
          overflowY="scroll"
          colSpan={6}
          bg="#E5E5E5"
        >
          <Flex justify="center" align="center" flexDirection="column">
            <Flex
              p={7}
              pt={0}
              mt={4}
              align="center"
              justify="flex-start"
              flexDirection="column"
              borderRadius="2vw 2vw 0 0"
              shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              bg="#AE0032"
              w="48vw"
              h="auto"
              minHeight="52.2vh"
            >
              <Flex
                m={4}
                mt={6}
                w="100%"
                h="1vh"
                align="center"
                justify="center"
              >
                <Text
                  textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                  fontWeight="bold"
                  color="#ffffff"
                  fontSize={18}
                >
                  Club Description
                </Text>
              </Flex>
              <Text color="#ffffff" fontSize={14}>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry's standard dummy
                text ever since the 1500s, when an unknown printer took a galley
                of type and scrambled it to make a type specimen book. It has
                survived not only five centuries, but also the leap into
                electronic typesetting, remaining essentially unchanged. It was
                popularised in the 1960s with the release of Letraset sheets
                containing Lorem Ipsum passages, and more recently with desktop
                publishing software like Aldus PageMaker including versions of
                Lorem Ipsum.
              </Text>
            </Flex>
          </Flex>
        </GridItem>
        <GridItem
          display="flex"
          justifyContent="flex-start"
          alignItems="center"
          flexDirection="column"
          rowSpan={7}
          colSpan={3}
          bg="#E5E5E5"
        >
          <Box
            display="flex"
            justifyContent="center"
            alignItems="center"
            textAlign="center"
            borderRadius="2vw"
            shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            mt={3}
            mr={3}
            ml={2}
            bg="#AE0032"
            w="23vw"
            h="4vh"
          >
            <Text
              fontStyle="normal"
              fontWeight="bold"
              fontSize="1.5vh"
              color="#ffffff"
              lineHeight="22px"
              display="flex"
              alignItems="center"
              textAlign="center"
              textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            >
              Club Members
            </Text>
          </Box>
          <Flex
            borderRadius="2vw"
            shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
            mr={3}
            ml={2}
            bg="#ffffff"
            w="23vw"
            h="85%"
            justify="flex-start"
            align="center"
            flexDir="column"
            p={4}
            overflowY="scroll"
            overflowX="hidden"
          >
            {arr.map((item) => {
              return <MemberCard name={item.name} url={item.url} />;
            })}
            {arr.map((item) => {
              return <MemberCard name={item.name} url={item.url} />;
            })}
          </Flex>
        </GridItem>
      </Grid>
    </Box>
  );
}
