import Head from "next/head";
import {
  Box,
  Grid,
  Flex,
  Text,
  FormControl,
  FormLabel,
  Input,
  Select,
  InputGroup,
  InputRightElement,
  Button,
} from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { NavBar } from "../components/navbar";

export default function HomePage() {
  return (
    <Box>
      <Head>
        <title>CRUx Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </Box>
  );
}
