import Head from "next/head";
import {
  Box,
  Grid,
  GridItem,
  Flex,
  Text,
  FormControl,
  FormLabel,
  Input,
  Select,
  InputGroup,
  InputRightElement,
  Button,
  Circle,
  Textarea,
} from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { NavBar } from "../components/navbar";

export default function HomePage() {
  return (
    <Box w="100%" h="100vh">
      <Head>
        <title>CRUx Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid
        overflow="hidden"
        h="93vh"
        templateRows="repeat(1, 1fr)"
        templateColumns="repeat(12, 1fr)"
        gap={0}
      >
        <GridItem colSpan={3} bg="#E5E5E5">
          <Flex
            position="sticky"
            justify="center"
            align="center"
            flexDirection="column"
          >
            <Flex>
              <Box
                borderRadius="2vw"
                shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                m={3}
                bg="#ffffff"
                w="23vw"
                h="10vw"
              >
                <Circle />
              </Box>
              <Flex>
                <Text></Text>
                <Text></Text>
              </Flex>
            </Flex>
            <Flex flexDir="column">
              <Box
                display="flex"
                justifyContent="center"
                alignItems="center"
                textAlign="center"
                borderRadius="2vw"
                shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                mt={1}
                mr={3}
                ml={3}
                bg="#AE0032"
                w="23vw"
                h="4vh"
              >
                <Text
                  fontStyle="normal"
                  fontWeight="bold"
                  fontSize="1.5vh"
                  color="#ffffff"
                  lineHeight="22px"
                  display="flex"
                  alignItems="center"
                  textAlign="center"
                  textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                >
                  Classmates
                </Text>
              </Box>
              <Box
                borderRadius="2vw"
                shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                ml={3}
                mr={3}
                bg="#ffffff"
                w="23vw"
                h="65vh"
              ></Box>
            </Flex>
          </Flex>
        </GridItem>
        <GridItem
          flexGrow="initial"
          overflowX="hidden"
          overflowY="scroll"
          colSpan={6}
          bg="#C4C4C4"
        >
          <Flex justify="center" align="center" flexDirection="column">
            <Box
              display="flex"
              justifyContent="flex-start"
              alignItems="center"
              textAlign="center"
              borderRadius="2vw"
              shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              mt={3}
              mr={3}
              ml={3}
              bg="#AE0032"
              w="48vw"
              h="4vh"
            >
              <Text
                ml={3}
                mb={1}
                mr={2}
                fontStyle="normal"
                fontWeight="light"
                fontSize="4vh"
                color="#ffffff"
                textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              >
                +
              </Text>
              <Text
                fontStyle="normal"
                fontWeight="bold"
                fontSize="1.5vh"
                color="#ffffff"
                lineHeight="22px"
                textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              >
                Create Post
              </Text>
            </Box>
            <Flex
              align="center"
              justify="center"
              flexDirection="column"
              borderRadius="2vw"
              shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
              bg="#ffffff"
              w="48vw"
              minH="9rem"
            >
              <Textarea
                bg="#E5E5E5"
                mt={3}
                ml={5}
                mr={5}
                w="45vw"
                minHeight="5rem"
                placeholder="Write a post..."
              />
              <Flex width="48vw" justify="space-between">
                <Flex>
                  <Button
                    display="flex"
                    _hover={{ bg: "#600008" }}
                    _active={{ bg: "#fff" }}
                    justifyContent="center"
                    alignItems="center"
                    textAlign="center"
                    borderRadius="2vw"
                    shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                    mt={2}
                    mr={1}
                    ml={5}
                    mb={1}
                    bg="#AE0032"
                    w="8vh"
                    h="30px"
                  >
                    {" "}
                    <img width="20px" src="/photo-128.png" />{" "}
                  </Button>
                  <Button
                    display="flex"
                    _hover={{ bg: "#600008" }}
                    _active={{ bg: "#fff" }}
                    justifyContent="center"
                    alignItems="center"
                    textAlign="center"
                    borderRadius="2vw"
                    shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                    mt={2}
                    mr={3}
                    ml={1}
                    mb={1}
                    bg="#AE0032"
                    w="8vh"
                    h="30px"
                  >
                    <img width="20px" src="/video-call-128.png" />
                  </Button>
                </Flex>
                <Button
                  display="flex"
                  _hover={{ bg: "#600008" }}
                  _active={{ bg: "#fff" }}
                  justifyContent="center"
                  alignItems="center"
                  textAlign="center"
                  borderRadius="2vw"
                  shadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                  mt={2}
                  mr={5}
                  ml={1}
                  mb={1}
                  bg="#AE0032"
                  w="8vh"
                  h="30px"
                >
                  {" "}
                  <Text fontSize="1.5vh" color="#ffffff" fontWeight="bold">
                    Post
                  </Text>{" "}
                </Button>
              </Flex>
            </Flex>
          </Flex>
        </GridItem>
        <GridItem colSpan={3} bg="#E5E5E5" />
      </Grid>
    </Box>
  );
}
