import Head from "next/head";
import { Box, Grid, GridItem } from "@chakra-ui/react";
import { NavBar } from "../components/navbar";
import { GridLeft } from "../components/homepagegrids/grid-left";
import { GridRight } from "../components/homepagegrids/grid-right";
import { GridCenter } from "../components/homepagegrids/grid-center";

export const arr = [
  {
    name: "Krishna Mahato",
    show: "block",
    url: "https://source.unsplash.com/WLUHO9A_xik/1440x960",
  },
  {
    name: "Abhay Anand",
    show: "none",
    url: "https://source.unsplash.com/DNE9iZ1Kqzk/1440x960",
  },
  {
    name: "Sushree Shriya Mishra",
    show: "none",
    url: "https://source.unsplash.com/6ccJQ5qPFvY/1440x960",
  },
  {
    name: "Swetapadma Das",
    show: "none",
    url: "https://source.unsplash.com/qTLyiHW1nIc/1440x960",
  },
  {
    name: "Ankit Singh",
    show: "none",
    url: "https://source.unsplash.com/fxX__3GRtsg/1440x960",
  },
];

export default function HomePage() {
  return (
    <Box w="100%" h="100vh">
      <Head>
        <title>CRUx Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid
        overflow="hidden"
        h="93vh"
        templateRows="repeat(1, 1fr)"
        templateColumns="repeat(12, 1fr)"
        gap={0}
      >
        <GridItem colSpan={3} bg="#E5E5E5">
          <GridLeft />
        </GridItem>
        <GridItem
          flexGrow="initial"
          overflowX="hidden"
          overflowY="scroll"
          colSpan={6}
          bg="#C4C4C4"
        >
          <GridCenter />
        </GridItem>
        <GridItem colSpan={3} bg="#E5E5E5">
          <GridRight />
        </GridItem>
      </Grid>
    </Box>
  );
}
