import Head from "next/head";
import {
  Box,
  Grid,
  GridItem,
  Flex,
  Circle,
  Editable,
  EditableInput,
  EditablePreview,
  useEditableControls,
  Button,
} from "@chakra-ui/react";
import { NavBar } from "../../components/navbar";
import { Bio } from "../../components/studentprofilegrids/Bio";
import { StudentPosts } from "../../components/studentprofilegrids/student-posts";
import { OtherInfo } from "../../components/studentprofilegrids/other-info";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";

export default function StudentProfile() {
  let globalState = useSelector((state) => state);
  const router = useRouter();
  const { studentProfile, name } = router.query;
  let i;
  let student = globalState.classmates.map((currStudent, idx) => {
    if (currStudent._id === studentProfile) {
      i = idx;
      return currStudent;
    }
  });
  const EditableControls = () => {
    const { isEditing, getSubmitButtonProps, getEditButtonProps } =
      useEditableControls();
    return isEditing ? (
      <Button
        _hover={{
          bg: "#600008",
        }}
        color="#ffffff"
        bg="#AE0032"
        h="1.75rem"
        size="sm"
        {...getSubmitButtonProps()}
      >
        OK
      </Button>
    ) : (
      <Flex ml={3} justifyContent="center">
        <Button
          _hover={{
            bg: "#600008",
          }}
          color="#ffffff"
          bg="#AE0032"
          h="1.75rem"
          size="sm"
          {...getEditButtonProps()}
        >
          Edit
        </Button>
      </Flex>
    );
  };
  return (
    <Box w="100%" h="100vh">
      <Head>
        <title>CRUx Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid
        overflow="hidden"
        h="93vh"
        templateRows="repeat(12, 1fr)"
        templateColumns="repeat(12, 1fr)"
        gap={0}
      >
        <GridItem colSpan={12} rowSpan={3} bg="#C4C4C4">
          <Box
            display="flex"
            h="31vh"
            flexGrow="1"
            bg={`url(${"https://source.unsplash.com/qTLyiHW1nIc/1440x960"})`}
            backgroundSize="cover"
            backgroundRepeat="no-repeat"
            backgroundPosition="center"
          />
        </GridItem>
        <GridItem colSpan={12} rowSpan={2} bg="#E5E5E5">
          <Flex
            flexDir="column"
            h="15.5vh"
            flexGrow="1"
            justify="flex-end"
            align="center"
          >
            <Circle shadow="lg" m={2} bg="white" size="25vh" />
            <Editable
              display="flex"
              justifyContent="center"
              alignItems="center"
              textAlign="center"
              defaultValue={student[i].name}
              fontSize="2xl"
              isPreviewFocusable={false}
            >
              <Flex justify="space-between" align="center">
                <Flex h={10} align="center" justify="center">
                  <EditablePreview
                    textShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
                    fontWeight="extrabold"
                    m={2}
                    mb={5}
                    h={8}
                  />
                  <EditableInput m={2} h={8} />
                </Flex>
                <Flex align="center" justify="flex-start" h={10}>
                  <EditableControls />
                </Flex>
              </Flex>
            </Editable>
          </Flex>
        </GridItem>
        <GridItem
          display="flex"
          justifyContent="flex-start"
          alignItems="center"
          flexDirection="column"
          rowSpan={7}
          colSpan={3}
          bg="#E5E5E5"
        >
          <StudentPosts />
        </GridItem>
        <GridItem
          rowSpan={7}
          flexGrow="initial"
          overflowX="hidden"
          overflowY="scroll"
          colSpan={6}
          bg="#E5E5E5"
        >
          <Bio bio={student[i].bio} />
        </GridItem>
        <GridItem
          display="flex"
          justifyContent="flex-start"
          alignItems="center"
          flexDirection="column"
          rowSpan={7}
          colSpan={3}
          bg="#E5E5E5"
        >
          <OtherInfo />
        </GridItem>
      </Grid>
    </Box>
  );
}
